from pathlib import Path

from fastapi import APIRouter, File, HTTPException, UploadFile
from fastapi.responses import FileResponse

from app.config import settings
from app.models.analysis_result import AnalysisResult
from app.services.analysis_pipeline import DataPilotAnalyzer
from app.tools.file_loader import DatasetLoadError, load_dataset
from app.utils.file_utils import (
    ensure_directory,
    generate_unique_filename,
)
from app.utils.logger import get_logger


logger = get_logger(__name__)


router = APIRouter(
    prefix="/api/v1",
    tags=["Analysis"],
)


analyzer = DataPilotAnalyzer()


@router.post(
    "/analyze",
    response_model=AnalysisResult,
)
async def analyze_dataset(
    file: UploadFile = File(...),
) -> AnalysisResult:
    """
    Upload a dataset and run the complete DataPilot analysis pipeline.

    The pipeline includes:

    - Dataset profiling
    - Data quality analysis
    - Dataset intelligence
    - ML intelligence
    - Feature intelligence
    - Quality scoring
    - Recommendations
    - Automated data preparation
    - Processed dataset generation
    """

    if not file.filename:
        raise HTTPException(
            status_code=400,
            detail="Filename is required.",
        )

    raw_directory = ensure_directory(
        settings.project_root
        / settings.raw_data_dir
    )

    unique_filename = generate_unique_filename(
        file.filename
    )

    destination = (
        raw_directory
        / unique_filename
    )

    logger.info(
        "Starting dataset analysis upload: %s",
        file.filename,
    )

    try:
        contents = await file.read()

        if not contents:
            raise HTTPException(
                status_code=400,
                detail="Uploaded file is empty.",
            )

        if (
            len(contents)
            > settings.max_file_size_bytes
        ):
            raise HTTPException(
                status_code=413,
                detail=(
                    "File exceeds the maximum allowed "
                    f"size of {settings.max_file_size_mb} MB."
                ),
            )

        destination.write_bytes(
            contents
        )

        logger.info(
            "Dataset saved temporarily: %s",
            destination,
        )

        dataframe = load_dataset(
            destination
        )

        logger.info(
            "Dataset loaded successfully: "
            "%s rows, %s columns",
            len(dataframe),
            len(dataframe.columns),
        )

        result = analyzer.analyze(
            dataframe=dataframe,
            filename=file.filename,
        )

        logger.info(
            "Dataset analysis completed: %s",
            file.filename,
        )

        return result

    except HTTPException:

        if destination.exists():
            destination.unlink()

        raise

    except DatasetLoadError as exc:

        if destination.exists():
            destination.unlink()

        logger.error(
            "Dataset loading failed: %s",
            exc,
        )

        raise HTTPException(
            status_code=400,
            detail=str(exc),
        ) from exc

    except Exception as exc:

        if destination.exists():
            destination.unlink()

        logger.exception(
            "Unexpected dataset analysis failure.",
        )

        raise HTTPException(
            status_code=500,
            detail=(
                "Unexpected error while analyzing "
                "the dataset."
            ),
        ) from exc


@router.get(
    "/datasets/{filename}",
    response_class=FileResponse,
)
async def download_processed_dataset(
    filename: str,
) -> FileResponse:
    """
    Download a processed dataset generated by DataPilot.
    """

    if not filename:
        raise HTTPException(
            status_code=400,
            detail="Filename is required.",
        )

    # ------------------------------------------------------------
    # Security: only allow a simple filename.
    # Prevent path traversal such as ../file.csv.
    # ------------------------------------------------------------

    requested_filename = Path(
        filename
    ).name

    if requested_filename != filename:
        raise HTTPException(
            status_code=400,
            detail="Invalid filename.",
        )

    if not filename.lower().endswith(".csv"):
        raise HTTPException(
            status_code=400,
            detail="Only CSV processed datasets can be downloaded.",
        )

    processed_directory = (
        settings.project_root
        / settings.processed_data_dir
    )

    processed_file = (
        processed_directory
        / filename
    )

    if not processed_file.exists():
        raise HTTPException(
            status_code=404,
            detail="Processed dataset not found.",
        )

    if not processed_file.is_file():
        raise HTTPException(
            status_code=404,
            detail="Processed dataset not found.",
        )

    logger.info(
        "Serving processed dataset: %s",
        processed_file,
    )

    return FileResponse(
        path=processed_file,
        media_type="text/csv",
        filename=filename,
    )